#!/usr/bin/python

def dump_test_list(tests):
	global bad_map
	global good_map
	for t in tests:
		print "<TR><TD>" + t + "</TD>"
		if t in bad_map:
			print "<TD style=\"background-color: #ff0000; \">BAD</TD>"
		elif t in good_map:
			print "<TD style=\"background-color: #00ff00; \">OK</TD>"
		else:
			print "<TD style=\"background-color: purple\">???</TD>"
		print "</TR>"


bad_tests = open("tests/traces-out/tests.bad", "r")
ok_tests = open("tests/traces-out/tests.ok", "r")

bad_map = dict()
good_map = dict()
all_tests = []
for f in bad_tests:
	bad_map[f[:-1]] = True
	all_tests.append(f[:-1])

for f in ok_tests:
	good_map[f[:-1]] = True
	all_tests.append(f[:-1])

print "<HTML><HEAD><TITLE>GENERATED BY MKREPORT.PY</TITLE></HEAD><BODY>"

print "<h1>TEST DUMP</h1><hr/>"

all_tests.sort()

unit_tests = filter(lambda x : "tests" in x, all_tests)
bin_tests = filter(lambda x : not "tests" in x, all_tests)

print "<p>Unit Tests:<br/>"
print "<TABLE><TR><TD>Test</TD><TD>Status</TD></TR>"
dump_test_list(unit_tests)
print "</TABLE></p>"

print "<p>Bin Tests:<br/>"
print "<TABLE><TR><TD>Test</TD><TD>Status</TD></TR>"
dump_test_list(bin_tests)
print "</TABLE></p>"


print "</BODY></HTML>"
